/// <reference types="astro/client" />

// Secrets (TURSO_DATABASE_URL, TURSO_AUTH_TOKEN, RESEND_API_KEY,
// CONTACT_TO_EMAIL, CONTACT_TOKEN_SECRET) are no longer read via
// import.meta.env — Cloudflare Workers expose them via
// `import { env } from 'cloudflare:workers'` instead (see
// src/db/client.ts, src/lib/contactToken.ts, src/lib/email.ts). The `Env`
// type for that import comes from worker-configuration.d.ts, generated by
// `npx wrangler types` from wrangler.jsonc — not hand-written here, to
// avoid it drifting out of sync with the actual bindings.
